import type {
  AdminDashboardDto,
  EventDetailDto,
  EventSummaryDto,
} from "../domain/event.types.js";
import type {
  WorkerDetailDto,
  WorkerHistoryEntryDto,
  WorkerSearchResultDto,
} from "../domain/worker.types.js";
import type {
  AuditHistoryItemDto,
  EventReportSummaryDto,
  StaffingReportItemDto,
} from "../domain/report.types.js";
import type { UserProfileRecord } from "../domain/auth.types.js";
import {
  resolveTodayDate,
  resolveTomorrowDate,
  resolveYesterdayDate,
  resolveOffsetBusinessDate,
} from "../shared/business-time.js";

const today = resolveTodayDate();
const tomorrow = resolveTomorrowDate();
const yesterday = resolveYesterdayDate();
const futureDate = resolveOffsetBusinessDate(5);

export const MOCK_ADMIN_PROFILE: UserProfileRecord = {
  userId: "00000000-0000-4000-8000-000000000001",
  workerNumber: 999,
  role: "ADMIN",
  fullName: "Local Test Admin",
  initials: "TA",
  phoneE164: "+15550000000",
  accountStatus: "ACTIVE",
  category: null,
};

export const MOCK_WORKERS: WorkerSearchResultDto[] = [
  {
    worker_id: "11111111-1111-4111-8111-111111111111",
    worker_number: 1001,
    full_name: "Arif Khan",
    category: "C",
    account_status: "ACTIVE",
    reliability_score: 88,
  },
  {
    worker_id: "22222222-2222-4222-8222-222222222222",
    worker_number: 1002,
    full_name: "Arif Ahmed",
    category: "B",
    account_status: "ACTIVE",
    reliability_score: 94,
  },
  {
    worker_id: "33333333-3333-4333-8333-333333333333",
    worker_number: 1003,
    full_name: "Rahul Sharma",
    category: "F",
    account_status: "ACTIVE",
    reliability_score: 72,
  },
  {
    worker_id: "44444444-4444-4444-8444-444444444444",
    worker_number: 1004,
    full_name: "Aman Verma",
    category: "A",
    account_status: "SUSPENDED",
    reliability_score: 81,
  },
];

export const MOCK_WORKER_DETAILS: Record<string, WorkerDetailDto> = {
  "11111111-1111-4111-8111-111111111111": {
    worker_id: "11111111-1111-4111-8111-111111111111",
    worker_number: 1001,
    full_name: "Arif Khan",
    role: "WORKER",
    account_status: "ACTIVE",
    category: "C",
    last_worker_category: "F",
    profile_completed_at: "2026-01-10T10:00:00Z",
    reliability_score: 88,
    reliability_state: "HEALTHY",
    reliability_sample_count: 20,
    reliability_present_count: 18,
    reliability_late_count: 2,
    reliability_absent_count: 0,
    reliability_worker_cancellation_count: 0,
    reliability_completed_event_count: 20,
    reliability_performance_event_count: 15,
    reliability_performance_average: 4.5,
    experience_level: "Experienced",
    education_status: "High School Graduate",
    has_previous_experience: true,
    experience_details: "2 years in hotel banquet catering and silver service.",
  },
  "22222222-2222-4222-8222-222222222222": {
    worker_id: "22222222-2222-4222-8222-222222222222",
    worker_number: 1002,
    full_name: "Arif Ahmed",
    role: "WORKER",
    account_status: "ACTIVE",
    category: "B",
    last_worker_category: "C",
    profile_completed_at: "2025-11-20T10:00:00Z",
    reliability_score: 94,
    reliability_state: "HEALTHY",
    reliability_sample_count: 35,
    reliability_present_count: 34,
    reliability_late_count: 1,
    reliability_absent_count: 0,
    reliability_worker_cancellation_count: 0,
    reliability_completed_event_count: 35,
    reliability_performance_event_count: 30,
    reliability_performance_average: 4.8,
    experience_level: "Veteran",
    education_status: "Bachelor of Arts",
    has_previous_experience: true,
    experience_details: "Extensive luxury wedding banquet and VIP lounge service.",
  },
  "33333333-3333-4333-8333-333333333333": {
    worker_id: "33333333-3333-4333-8333-333333333333",
    worker_number: 1003,
    full_name: "Rahul Sharma",
    role: "WORKER",
    account_status: "ACTIVE",
    category: "F",
    last_worker_category: null,
    profile_completed_at: "2026-03-01T10:00:00Z",
    reliability_score: 72,
    reliability_state: "MONITORED",
    reliability_sample_count: 5,
    reliability_present_count: 4,
    reliability_late_count: 1,
    reliability_absent_count: 0,
    reliability_worker_cancellation_count: 1,
    reliability_completed_event_count: 4,
    reliability_performance_event_count: 3,
    reliability_performance_average: 3.8,
    experience_level: "Fresher",
    education_status: "Undergraduate",
    has_previous_experience: false,
    experience_details: null,
  },
  "44444444-4444-4444-8444-444444444444": {
    worker_id: "44444444-4444-4444-8444-444444444444",
    worker_number: 1004,
    full_name: "Aman Verma",
    role: "WORKER",
    account_status: "SUSPENDED",
    category: "A",
    last_worker_category: "A",
    profile_completed_at: "2025-08-15T10:00:00Z",
    reliability_score: 81,
    reliability_state: "SUSPENDED",
    reliability_sample_count: 28,
    reliability_present_count: 25,
    reliability_late_count: 2,
    reliability_absent_count: 1,
    reliability_worker_cancellation_count: 2,
    reliability_completed_event_count: 27,
    reliability_performance_event_count: 25,
    reliability_performance_average: 4.2,
    experience_level: "Senior",
    education_status: "Diploma in Hospitality",
    has_previous_experience: true,
    experience_details: "Captain support and buffet coordinator.",
  },
};

export const MOCK_WORKER_HISTORY: Record<string, WorkerHistoryEntryDto[]> = {
  "11111111-1111-4111-8111-111111111111": [
    {
      history_type: "REGISTRATION",
      action: "ACCOUNT_APPROVED",
      old_value: "PENDING_APPROVAL",
      new_value: "ACTIVE",
      actor_id: MOCK_ADMIN_PROFILE.userId,
      actor_role: "ADMIN",
      reason: "Initial profile verification complete",
      created_at: "2026-01-10T10:00:00Z",
    },
    {
      history_type: "TIER_CHANGE",
      action: "TIER_PROMOTED",
      old_value: "F",
      new_value: "C",
      actor_id: MOCK_ADMIN_PROFILE.userId,
      actor_role: "ADMIN",
      reason: "Completed 10 shifts with positive supervisor ratings",
      created_at: "2026-02-15T14:30:00Z",
    },
  ],
  "22222222-2222-4222-8222-222222222222": [
    {
      history_type: "TIER_CHANGE",
      action: "TIER_PROMOTED",
      old_value: "C",
      new_value: "B",
      actor_id: MOCK_ADMIN_PROFILE.userId,
      actor_role: "ADMIN",
      reason: "Exemplary performance during high-volume wedding season",
      created_at: "2026-03-01T11:00:00Z",
    },
  ],
  "33333333-3333-4333-8333-333333333333": [
    {
      history_type: "TIER_CHANGE",
      action: "TIER_ASSIGNED",
      old_value: null,
      new_value: "F",
      actor_id: MOCK_ADMIN_PROFILE.userId,
      actor_role: "ADMIN",
      reason: "Onboarded as fresh entrant",
      created_at: "2026-04-01T09:00:00Z",
    },
  ],
  "44444444-4444-4444-8444-444444444444": [
    {
      history_type: "STATUS_CHANGE",
      action: "ACCOUNT_SUSPENDED",
      old_value: "ACTIVE",
      new_value: "SUSPENDED",
      actor_id: MOCK_ADMIN_PROFILE.userId,
      actor_role: "ADMIN",
      reason: "Unexplained no-show at Royal Garden event",
      created_at: "2026-05-12T16:20:00Z",
    },
  ],
};

export const MOCK_EVENTS: EventSummaryDto[] = [
  {
    id: "aaaa1111-1111-4aaa-8aaa-111111111111",
    title: "Taj Palace Wedding",
    event_type: "WEDDING",
    venue_name: "Taj Palace Banquet Hall",
    event_date: today,
    reporting_at: `${today}T15:00:00Z`,
    required_worker_count: 15,
    daily_wage: 1200,
    currency_code: "INR",
    event_status: "IN_PROGRESS",
    recruitment_status: "FULL",
    tier_strategy: "STANDARD",
    version: 1,
  },
  {
    id: "bbbb2222-2222-4bbb-8bbb-222222222222",
    title: "Hyatt Wedding",
    event_type: "WEDDING",
    venue_name: "Grand Hyatt Ballroom",
    event_date: tomorrow,
    reporting_at: `${tomorrow}T16:30:00Z`,
    required_worker_count: 20,
    daily_wage: 1300,
    currency_code: "INR",
    event_status: "PUBLISHED",
    recruitment_status: "OPEN",
    tier_strategy: "URGENT",
    version: 2,
  },
  {
    id: "cccc3333-3333-4ccc-8ccc-333333333333",
    title: "Corporate Meetup",
    event_type: "CORPORATE",
    venue_name: "TechHub Convention Center",
    event_date: today,
    reporting_at: `${today}T08:00:00Z`,
    required_worker_count: 8,
    daily_wage: 1000,
    currency_code: "INR",
    event_status: "UPCOMING",
    recruitment_status: "OPEN",
    tier_strategy: "STANDARD",
    version: 1,
  },
  {
    id: "dddd4444-4444-4ddd-8ddd-444444444444",
    title: "Royal Garden Reception",
    event_type: "RECEPTION",
    venue_name: "Royal Gardens Lawn",
    event_date: yesterday,
    reporting_at: `${yesterday}T18:00:00Z`,
    required_worker_count: 12,
    daily_wage: 1150,
    currency_code: "INR",
    event_status: "COMPLETED",
    recruitment_status: "CLOSED",
    tier_strategy: "STANDARD",
    version: 1,
  },
  {
    id: "eeee5555-5555-4eee-8eee-555555555555",
    title: "Tech Conference",
    event_type: "CONFERENCE",
    venue_name: "Expo Center Hall A",
    event_date: futureDate,
    reporting_at: `${futureDate}T09:00:00Z`,
    required_worker_count: 25,
    daily_wage: 1400,
    currency_code: "INR",
    event_status: "DRAFT",
    recruitment_status: "NOT_OPEN",
    tier_strategy: "CUSTOM",
    version: 1,
  },
];

export const MOCK_EVENT_DETAILS: Record<string, EventDetailDto> = {
  "aaaa1111-1111-4aaa-8aaa-111111111111": {
    id: "aaaa1111-1111-4aaa-8aaa-111111111111",
    title: "Taj Palace Wedding",
    event_type: "WEDDING",
    venue_name: "Taj Palace Banquet Hall",
    maps_url: "https://maps.google.com/?q=Taj+Palace",
    event_date: today,
    reporting_at: `${today}T15:00:00Z`,
    work_starts_at: `${today}T16:00:00Z`,
    expected_ends_at: `${today}T23:30:00Z`,
    required_worker_count: 15,
    confirmed_count: 15,
    waitlist_count: 3,
    daily_wage: 1200,
    currency_code: "INR",
    event_status: "IN_PROGRESS",
    recruitment_status: "FULL",
    tier_strategy: "STANDARD",
    version: 1,
    instructions: "Check in at staff entrance B. Bring government ID.",
    dress_code: "White shirt, black trousers, black leather shoes.",
    open_review_flags: 0,
    leaders: [
      {
        user_id: "00000000-0000-4000-8000-000000000002",
        full_name: "Vikas Malhotra",
        leader_role: "CAPTAIN",
      },
    ],
    requirements: [
      {
        id: "req-1",
        name: "Formal Black Shoes",
        description: "Polished black shoes required",
        is_mandatory: true,
        acknowledgement_required: true,
        extra_allowance_amount: 0,
        display_order: 1,
      },
    ],
    allowances: [
      {
        id: "all-1",
        label: "Late Night Travel Allowance",
        description: "Provided for shifts ending after 23:00",
        amount: 150,
        display_order: 1,
      },
    ],
  },
  "bbbb2222-2222-4bbb-8bbb-222222222222": {
    id: "bbbb2222-2222-4bbb-8bbb-222222222222",
    title: "Hyatt Wedding",
    event_type: "WEDDING",
    venue_name: "Grand Hyatt Ballroom",
    maps_url: "https://maps.google.com/?q=Grand+Hyatt",
    event_date: tomorrow,
    reporting_at: `${tomorrow}T16:30:00Z`,
    work_starts_at: `${tomorrow}T17:30:00Z`,
    expected_ends_at: `${tomorrow}T01:00:00Z`,
    required_worker_count: 20,
    confirmed_count: 14,
    waitlist_count: 0,
    daily_wage: 1300,
    currency_code: "INR",
    event_status: "PUBLISHED",
    recruitment_status: "OPEN",
    tier_strategy: "URGENT",
    version: 2,
    instructions: "Urgent recruitment needed: 6 vacant server positions remaining.",
    dress_code: "Formal black suit or traditional banquet uniform.",
    open_review_flags: 0,
    leaders: [
      {
        user_id: "00000000-0000-4000-8000-000000000003",
        full_name: "Sunil Verma",
        leader_role: "SUPERVISOR",
      },
    ],
    requirements: [],
    allowances: [
      {
        id: "all-2",
        label: "Urgent Shift Bonus",
        description: "Provided for short notice confirmation",
        amount: 200,
        display_order: 1,
      },
    ],
  },
  "cccc3333-3333-4ccc-8ccc-333333333333": {
    id: "cccc3333-3333-4ccc-8ccc-333333333333",
    title: "Corporate Meetup",
    event_type: "CORPORATE",
    venue_name: "TechHub Convention Center",
    maps_url: null,
    event_date: today,
    reporting_at: `${today}T08:00:00Z`,
    work_starts_at: `${today}T08:30:00Z`,
    expected_ends_at: `${today}T17:00:00Z`,
    required_worker_count: 8,
    confirmed_count: 8,
    waitlist_count: 1,
    daily_wage: 1000,
    currency_code: "INR",
    event_status: "UPCOMING",
    recruitment_status: "OPEN",
    tier_strategy: "STANDARD",
    version: 1,
    instructions: "Registration desk assistance and coffee break hospitality.",
    dress_code: "Smart casuals with navy blue collared shirt.",
    open_review_flags: 0,
    leaders: [],
    requirements: [],
    allowances: [],
  },
  "dddd4444-4444-4ddd-8ddd-444444444444": {
    id: "dddd4444-4444-4ddd-8ddd-444444444444",
    title: "Royal Garden Reception",
    event_type: "RECEPTION",
    venue_name: "Royal Gardens Lawn",
    maps_url: null,
    event_date: yesterday,
    reporting_at: `${yesterday}T18:00:00Z`,
    work_starts_at: `${yesterday}T19:00:00Z`,
    expected_ends_at: `${yesterday}T23:45:00Z`,
    required_worker_count: 12,
    confirmed_count: 12,
    waitlist_count: 2,
    daily_wage: 1150,
    currency_code: "INR",
    event_status: "COMPLETED",
    recruitment_status: "CLOSED",
    tier_strategy: "STANDARD",
    version: 1,
    instructions: "Completed successfully with full attendance.",
    dress_code: "Standard banquet uniform.",
    open_review_flags: 0,
    leaders: [],
    requirements: [],
    allowances: [],
  },
  "eeee5555-5555-4eee-8eee-555555555555": {
    id: "eeee5555-5555-4eee-8eee-555555555555",
    title: "Tech Conference",
    event_type: "CONFERENCE",
    venue_name: "Expo Center Hall A",
    maps_url: null,
    event_date: futureDate,
    reporting_at: `${futureDate}T09:00:00Z`,
    work_starts_at: `${futureDate}T09:30:00Z`,
    expected_ends_at: `${futureDate}T18:00:00Z`,
    required_worker_count: 25,
    confirmed_count: 0,
    waitlist_count: 0,
    daily_wage: 1400,
    currency_code: "INR",
    event_status: "DRAFT",
    recruitment_status: "NOT_OPEN",
    tier_strategy: "CUSTOM",
    version: 1,
    instructions: "Draft event: awaiting client confirmation of booth staff counts.",
    dress_code: "Black blazer and trousers.",
    open_review_flags: 0,
    leaders: [],
    requirements: [],
    allowances: [],
  },
};

export const MOCK_DASHBOARD: AdminDashboardDto = {
  today_event_count: 2,
  draft_count: 1,
  published_count: 1,
  upcoming_count: 1,
  in_progress_count: 1,
  completed_count: 1,
  open_review_flag_count: 0,
  required_today_count: 23,
  confirmed_today_count: 23,
  vacant_today_count: 0,
};

export const MOCK_EVENT_REPORTS: Record<
  string,
  {
    summary: EventReportSummaryDto;
    staffing: StaffingReportItemDto[];
    audit: AuditHistoryItemDto[];
  }
> = {
  "aaaa1111-1111-4aaa-8aaa-111111111111": {
    summary: {
      event_id: "aaaa1111-1111-4aaa-8aaa-111111111111",
      title: "Taj Palace Wedding",
      event_type: "WEDDING",
      venue_name: "Taj Palace Banquet Hall",
      event_date: today,
      reporting_at: `${today}T15:00:00Z`,
      work_starts_at: `${today}T16:00:00Z`,
      expected_ends_at: `${today}T23:30:00Z`,
      required_worker_count: 15,
      confirmed_worker_count: 15,
      daily_wage: 1200,
      allowance_total: 2250,
      total_worker_pay_display: 20250,
      currency_code: "INR",
      event_status: "IN_PROGRESS",
      recruitment_status: "FULL",
      attendance_total: 15,
      attendance_not_marked: 0,
      attendance_present: 15,
      attendance_late: 0,
      attendance_absent: 0,
    },
    staffing: [
      {
        assignment_id: "asg-001",
        worker_id: "11111111-1111-4111-8111-111111111111",
        worker_number: 1001,
        full_name: "Arif Khan",
        category_at_confirmation: "C",
        assignment_status: "CONFIRMED",
        confirmed_at: `${today}T10:00:00Z`,
        attendance_status: "PRESENT",
        attendance_marked_at: `${today}T14:50:00Z`,
        attendance_notes: "Checked in on time",
        daily_wage: 1200,
        allowance_total: 150,
        total_pay_display: 1350,
        currency_code: "INR",
      },
      {
        assignment_id: "asg-002",
        worker_id: "22222222-2222-4222-8222-222222222222",
        worker_number: 1002,
        full_name: "Arif Ahmed",
        category_at_confirmation: "B",
        assignment_status: "CONFIRMED",
        confirmed_at: `${today}T10:15:00Z`,
        attendance_status: "PRESENT",
        attendance_marked_at: `${today}T14:55:00Z`,
        attendance_notes: "Checked in on time",
        daily_wage: 1300,
        allowance_total: 150,
        total_pay_display: 1450,
        currency_code: "INR",
      },
    ],
    audit: [
      {
        history_source: "EVENT_AUDIT",
        action: "STATUS_CHANGE_TO_IN_PROGRESS",
        actor_id: MOCK_ADMIN_PROFILE.userId,
        actor_role: "ADMIN",
        entity_type: "event",
        entity_id: "aaaa1111-1111-4aaa-8aaa-111111111111",
        reason: "Event started on schedule with 15 checked-in workers.",
        created_at: `${today}T15:00:00Z`,
      },
    ],
  },
  "bbbb2222-2222-4bbb-8bbb-222222222222": {
    summary: {
      event_id: "bbbb2222-2222-4bbb-8bbb-222222222222",
      title: "Hyatt Wedding",
      event_type: "WEDDING",
      venue_name: "Grand Hyatt Ballroom",
      event_date: tomorrow,
      reporting_at: `${tomorrow}T16:30:00Z`,
      work_starts_at: `${tomorrow}T17:30:00Z`,
      expected_ends_at: `${tomorrow}T01:00:00Z`,
      required_worker_count: 20,
      confirmed_worker_count: 14,
      daily_wage: 1300,
      allowance_total: 2800,
      total_worker_pay_display: 21000,
      currency_code: "INR",
      event_status: "PUBLISHED",
      recruitment_status: "OPEN",
      attendance_total: 14,
      attendance_not_marked: 14,
      attendance_present: 0,
      attendance_late: 0,
      attendance_absent: 0,
    },
    staffing: [
      {
        assignment_id: "asg-003",
        worker_id: "22222222-2222-4222-8222-222222222222",
        worker_number: 1002,
        full_name: "Arif Ahmed",
        category_at_confirmation: "B",
        assignment_status: "CONFIRMED",
        confirmed_at: `${yesterday}T15:00:00Z`,
        attendance_status: "NOT_MARKED",
        attendance_marked_at: null,
        attendance_notes: null,
        daily_wage: 1300,
        allowance_total: 200,
        total_pay_display: 1500,
        currency_code: "INR",
      },
    ],
    audit: [
      {
        history_source: "EVENT_AUDIT",
        action: "EVENT_PUBLISHED",
        actor_id: MOCK_ADMIN_PROFILE.userId,
        actor_role: "ADMIN",
        entity_type: "event",
        entity_id: "bbbb2222-2222-4bbb-8bbb-222222222222",
        reason: "Recruitment opened for 20 positions with urgent tier strategy.",
        created_at: `${yesterday}T12:00:00Z`,
      },
    ],
  },
};
